[project]
name = "ComfyUI-Mayo-Nodes"
description = "Sleek and responsive custom nodes for latent aspect ratio management, time formatting, and dynamic dropdown properties."
version = "0.3.3"
license = "MIT" 

[project.urls]
Repository = "https://github.com/Pasu2k/comfyui-mayo-nodes"
Documentation = "https://github.com/Pasu2k/comfyui-mayo-nodes"
"Bug Tracker" = "https://github.com/Pasu2k/comfyui-mayo-nodes/issues"

[tool.comfy]
PublisherId = "mayo"
DisplayName = "ComfyUI Mayo Nodes"
Icon = "https://raw.githubusercontent.com/Pasu2k/comfyui-mayo-nodes/refs/heads/main/img/mayo-nodes.jpg"

Nodes = [
    "MayoDropdown",
    "MayoLatent",
    "MayoTimeFormatter"
]